### ISSUE TITLE
Replace string with char in filterbank-core

### ISSUE THREAD

**Issue by RonaldPhilipsen** [AUAS-Pulsar/Asteria#2]
[ 30%] Building CXX object libAsteria/filterbank-core/src/CMakeFiles/filterbank-core.dir/filterbank-core.cpp.o
In file included from /sfs/Asteria/libAsteria/filterbank-core/src/../include/filterbank-core.h:15:0,
                 from /sfs/Asteria/libAsteria/filterbank-core/src/filterbank-core.cpp:1:
/sfs/Asteria/libAsteria/filterbank-core/src/../include/HeaderParam.h:13:17: error: invalid conversion from ‘const char*’ to ‘char’ [-fpermissive]
  char s[80]{"\0"};
                 ^
/sfs/Asteria/libAsteria/filterbank-core/src/filterbank-core.cpp: In member function ‘char* filterbank::read_string(uint32_t&)’:
/sfs/Asteria/libAsteria/filterbank-core/src/filterbank-core.cpp:315:60: warning: non-constant array size in new, unable to verify length of initializer-list [enabled by default]
    char* buffer = new char[(((uint64_t)keylen) + 1)]{ '\0' };
                                                            ^
make[2]: *** [libAsteria/filterbank-core/src/CMakeFiles/filterbank-core.dir/filterbank-core.cpp.o] Error 1
make[1]: *** [libAsteria/filterbank-core/src/CMakeFiles/filterbank-core.dir/all] Error 2

**Comment by thomasstolk** [comment]
30 sp
